# Generated by Django 5.2.8 on 2025-12-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_friendship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles_owned', to='users.arguserprofile')),
                ('participants', models.ManyToManyField(related_name='puzzles_participated', to='users.arguserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SourceTextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_text', models.TextField()),
                ('plain_text', models.TextField()),
                ('method', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('parent_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_entries', to='puzzles.sourcetextentry')),
                ('puzzle_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_arg', to='puzzles.puzzlehub')),
                ('solver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cipher_entries', to='users.arguserprofile')),
            ],
        ),
    ]
