# Generated by Django 5.2.8 on 2025-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_puzzlehub_id_alter_sourcetextentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlehub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puzzlehub',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
